version: "3"

services:
  api:
    container_name: dev-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: python index.py
    ports:
      - 5000:5000
    volumes:
      - ./api/src:/usr/api/src
    restart: always
    environment:
      - STAGE=dev
    env_file:
      - .env
