version: "3"

services:
  api:
    container_name: dev-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: python index.py
    ports:
      - 5000:5000
    volumes:
      - ./api/src:/usr/api/src
    restart: always
    environment:
      - STAGE=dev
    env_file:
      - .env
    networks:
      - app-network
  dev-postgres:
    container_name: dev-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./dev-db/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
