version: "3"

services:
  api:
    container_name: prod-api
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: uwsgi --ini uwsgi.ini
    ports:
      - 5000:5000
    restart: always
    env_file:
      - .env
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
    - api
    ports:
    - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
