FROM python:3.10

WORKDIR /usr/api

COPY index.py requirements.txt uwsgi.ini ./

RUN pip install -r requirements.txt \
    && pip install uwsgi

COPY src/ ./src/

EXPOSE 5000

CMD ["uwsgi", "--ini", "uwsgi.ini"]
